import fs from 'node:fs';
import assert from 'node:assert/strict';
const js=fs.readFileSync(new URL('../v28-counter-speed.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../v28-counter-speed.css',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
assert.match(js,/service\s*===\s*'dryclean'\s*\|\|\s*service\s*===\s*'alterations'/);
assert.doesNotMatch(js,/service\s*===\s*'shirts'\s*\|\|\s*service\s*===\s*'alterations'/);
assert.match(js,/v28PickAndAddColor/);
assert.match(js,/\[1,2,3,4,5,6,7,8,9\]/);
assert.match(js,/2\. Quantity/);
assert.match(js,/1\. Garment Type/);
assert.match(js,/More Garment Types/);
assert.match(js,/Select bag color/);
assert.match(js,/autoServiceDefaults/);
assert.match(js,/v28ConfirmPreferenceOverride/);
assert.match(js,/ArrowUp','ArrowDown/);
assert.match(css,/v28-big-search/);
assert.match(css,/v28-color-grid/);
assert.match(css,/v28-sticky-visit/);
assert.match(css,/v28-shirt-qty/);
assert.match(html,/v28-counter-speed\.js/);
assert.match(html,/v28-counter-speed\.css/);
console.log('V28.3 guided counter checks passed');
