/* Hattan V28.2 — zero-scroll Drop Off kiosk + EN/ES/ZH training labels */
(function(){
const T={
 en:{customer:'Find Customer',search:'Name / phone / address / customer #',service:'Choose Service',dryclean:'Dry Cleaning',shirts:'Laundered Shirts',washfold:'Wash & Fold',alterations:'Alterations',garment:'Choose Garment',qty:'How many?',color:'Choose Color',instructions:'Instructions & Finish',next:'Next',back:'Back',more:'More',pickup:'Customer Pickup',delivery:'Delivery',complete:'Complete & Print',empty:'No items yet',ticket:'Current Ticket',edit:'Edit',remove:'Remove',crease:'Crease',nocrease:'No Crease',stain:'Stain',delicate:'Delicate',defective:'Defective',rush:'RUSH',note:'Ticket note',pounds:'Enter pounds',add:'Add to Ticket',packaging:'Packaging',hanger:'On Hanger',box:'Boxed',starch:'Starch',none:'None',light:'Light',medium:'Medium',heavy:'Heavy'},
 es:{customer:'Buscar cliente',search:'Nombre / teléfono / dirección / # cliente',service:'Elegir servicio',dryclean:'Limpieza en seco',shirts:'Camisas lavadas',washfold:'Lavado y doblado',alterations:'Arreglos',garment:'Elegir prenda',qty:'¿Cuántas?',color:'Elegir color',instructions:'Instrucciones y finalizar',next:'Siguiente',back:'Atrás',more:'Más',pickup:'Recoge cliente',delivery:'Entrega',complete:'Completar e imprimir',empty:'Sin prendas todavía',ticket:'Ticket actual',edit:'Editar',remove:'Quitar',crease:'Con raya',nocrease:'Sin raya',stain:'Mancha',delicate:'Delicado',defective:'Defectuoso',rush:'URGENTE',note:'Nota del ticket',pounds:'Ingrese libras',add:'Agregar al ticket',packaging:'Empaque',hanger:'En gancho',box:'En caja',starch:'Almidón',none:'Ninguno',light:'Ligero',medium:'Medio',heavy:'Fuerte'},
 zh:{customer:'查找顾客',search:'姓名 / 电话 / 地址 / 顾客编号',service:'选择服务',dryclean:'干洗',shirts:'衬衫水洗',washfold:'洗衣折叠',alterations:'修改衣服',garment:'选择衣物',qty:'数量',color:'选择颜色',instructions:'说明与完成',next:'下一步',back:'返回',more:'更多',pickup:'顾客自取',delivery:'送货',complete:'完成并打印',empty:'尚未添加衣物',ticket:'当前票据',edit:'编辑',remove:'删除',crease:'裤线',nocrease:'不要裤线',stain:'污渍',delicate:'精细衣物',defective:'有瑕疵',rush:'加急',note:'票据备注',pounds:'输入磅数',add:'加入票据',packaging:'包装',hanger:'挂装',box:'盒装',starch:'上浆',none:'无',light:'轻',medium:'中',heavy:'重'}
};
let K={step:'customer',lang:localStorage.getItem('hattanCounterLang')||'en',qty:1,garment:null,material:'cotton',showMore:false};
function tr(k){return (T[K.lang]||T.en)[k]||k} function esc2(s){return window.esc?esc(s):String(s||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
window.v282Lang=function(l){K.lang=l;localStorage.setItem('hattanCounterLang',l);renderPosContent()};
window.v282Step=function(s){K.step=s;renderPosContent()};
window.v282Service=function(s){counterDraft.serviceMode=s;K.step=s==='dryclean'?'garment':s;renderPosContent()};
window.v282Qty=function(n){K.qty=n;K.step='color';renderPosContent()};
window.v282Garment=function(id){K.garment=id;K.step='qty';renderPosContent()};
window.v282Color=function(id){counterDraft.builder.garmentId=K.garment;counterDraft.builder.qty=K.qty;counterDraft.builder.colorId=id;counterDraft.builder.materialId=counterDraft.builder.materialId||'cotton';posAddGarmentToTicket();K.garment=null;K.qty=1;K.step='garment'};
window.v282Pick=function(id){posPickCustomer(id);K.step='service'};
window.v282Search=function(v){posCustomerSearch=v;renderPosContent();setTimeout(()=>{let x=document.getElementById('v282search');if(x){x.focus();x.setSelectionRange(x.value.length,x.value.length)}},0)};
window.v282More=function(){K.showMore=!K.showMore;renderPosContent()};
window.v282SetFulfill=function(v){counterDraft.fulfillment=v;renderPosContent()};
function ticket(){let d=counterDraft;return `<div class="v282-ticket"><h3>${tr('ticket')} · ${v4TicketNumber()}</h3><div class="v282-lines">${d.items.length?d.items.map((it,i)=>{let g=garmentById(it.garmentId),c=colorById(it.colorId);return `<div class="v282-line"><strong>${esc2(g?.name||'Item')} × ${it.qty}</strong><div>${esc2(c?.name||'')} ${it.garmentNote?' · '+esc2(it.garmentNote):''}</div><button onclick="posRemoveItem(${i})">${tr('remove')}</button></div>`}).join(''):`<div class="ticket-empty">${tr('empty')}</div>`}</div><div class="v282-total">${money(posTicketTotal())}</div><div class="v282-actions"><button class="${d.fulfillment==='pickup'?'sel':''}" onclick="v282SetFulfill('pickup')">${tr('pickup')}</button><button class="${d.fulfillment==='delivery'?'sel':''}" onclick="v282SetFulfill('delivery')">${tr('delivery')}</button>${d.items.length?`<button class="v282-complete" onclick="posCompleteDropOff()">${tr('complete')}</button>`:''}</div></div>`}
function header(c){return `<div class="v282-head"><div>${c?`<div class="v282-customer">${esc2(c.name)} · ${esc2(c.customerNumber||'')}</div><div class="v282-sub">${esc2(c.phone||'')} ${c.address?' · '+esc2(c.address):''}</div>`:`<div class="v282-customer">Hattan Drop Off</div><div class="v282-sub">V28.2 · Zero-scroll counter</div>`}</div><div class="v282-lang"><button class="${K.lang==='en'?'on':''}" onclick="v282Lang('en')">EN</button><button class="${K.lang==='es'?'on':''}" onclick="v282Lang('es')">ES</button><button class="${K.lang==='zh'?'on':''}" onclick="v282Lang('zh')">中文</button></div></div>`}
function stageCustomer(){let q=posCustomerSearch.trim().toLowerCase();let r=q?state.customers.filter(c=>[c.name,c.phone,c.address,c.customerNumber].some(x=>String(x||'').toLowerCase().includes(q))).slice(0,8):[];return `<h2 class="v282-title">${tr('customer')}</h2><input id="v282search" autofocus class="v282-search" placeholder="${tr('search')}" value="${esc2(posCustomerSearch)}" oninput="v282Search(this.value)"><div class="v282-results">${r.map(c=>`<div class="v282-result" onclick="v282Pick('${c.id}')">${esc2(c.name)}<small style="display:block">${esc2(c.phone||'')} · ${esc2(c.address||c.customerNumber||'')}</small></div>`).join('')}</div>`}
function stageService(){return `<h2 class="v282-title">${tr('service')}</h2><div class="v282-grid"><button class="v282-big" onclick="v282Service('dryclean')">${tr('dryclean')}</button><button class="v282-big" onclick="v282Service('shirts')">${tr('shirts')}</button><button class="v282-big" onclick="v282Service('washfold')">${tr('washfold')}</button><button class="v282-big" onclick="v282Service('alterations')">${tr('alterations')}</button></div>`}
function stageGarment(){let ids=(state.interfaceSettings?.drycleanOrder||[]);let show=K.showMore?ids:ids.slice(0,9);return `<h2 class="v282-title">${tr('garment')}</h2><div class="v282-grid">${show.map(id=>{let g=garmentById(id);return g?`<button class="v282-big" onclick="v282Garment('${id}')">${esc2(g.name)}<small>${money(g.basePrice)}</small></button>`:''}).join('')}${ids.length>9?`<button class="v282-big" onclick="v282More()">${tr('more')} →</button>`:''}</div>`}
function stageQty(){return `<h2 class="v282-title">${tr('qty')}</h2><div class="v282-qty">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<button onclick="v282Qty(${n})">${n}</button>`).join('')}</div>`}
function stageColor(){return `<h2 class="v282-title">${tr('color')}</h2><div class="v282-colors">${GARMENT_COLORS.map(c=>`<button class="v282-color" onclick="v282Color('${c.id}')"><i style="background:${c.sw}"></i>${esc2(c.name)}</button>`).join('')}</div>`}
function stageShirts(){return `<h2 class="v282-title">${tr('shirts')}</h2><div class="v282-qty">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<button onclick="counterDraft.shirts.qty=${n};renderPosContent()" class="${counterDraft.shirts.qty===n?'sel':''}">${n}</button>`).join('')}</div><div class="v282-chips" style="margin-top:14px"><button class="v282-chip ${counterDraft.shirts.packaging==='hanger'?'sel':''}" onclick="v4SetShirtPackaging('hanger')">${tr('hanger')}</button><button class="v282-chip ${counterDraft.shirts.packaging==='box'?'sel':''}" onclick="v4SetShirtPackaging('box')">${tr('box')}</button>${['None','Light','Medium','Heavy'].map(s=>`<button class="v282-chip ${counterDraft.shirts.starch===s?'sel':''}" onclick="v4SetStarch('${s}')">${tr(s.toLowerCase())}</button>`).join('')}</div><div class="v282-footer"><button class="v282-next" onclick="v4AddLaunderedShirts();K.step='service';renderPosContent()">${tr('add')}</button></div>`}
function stageWF(){return `<h2 class="v282-title">${tr('washfold')}</h2><input class="v282-field" type="number" step=".1" placeholder="${tr('pounds')}" value="${esc2(counterDraft.wf.pounds)}" oninput="v4SetWfField('pounds',this.value)"><div class="v282-grid four">${['Black','White','Blue','Red','Green','Gray','Pink','Other'].map(c=>`<button class="v282-big ${counterDraft.wf.bagColor===c?'sel':''}" onclick="v4SetWfField('bagColor','${c}');renderPosContent()">${c}</button>`).join('')}</div><div class="v282-footer"><button class="v282-next" onclick="v4AddWashFold();K.step='service';renderPosContent()">${tr('add')}</button></div>`}
function stageAlt(){let arr=(state.interfaceSettings?.alterationOrder||[]).slice(0,12);return `<h2 class="v282-title">${tr('alterations')}</h2><div class="v282-grid four">${arr.map(id=>{let a=ALTERATION_VARIANTS.find(x=>x.id===id);return a?`<button class="v282-big ${counterDraft.alteration.variantId===id?'sel':''}" onclick="v4SetAlterVariant('${id}')">${esc2(a.garment)}<small>${esc2(a.name)} · ${a.price?money(a.price):'Quoted'}</small></button>`:''}).join('')}</div><input class="v282-field" style="margin-top:12px" placeholder="Details / notes" value="${esc2(counterDraft.alteration.additionalInfo)}" oninput="counterDraft.alteration.additionalInfo=this.value"><div class="v282-footer"><button class="v282-next" onclick="v4AddAlteration();K.step='service';renderPosContent()">${tr('add')}</button></div>`}
function stageFinish(){return `<h2 class="v282-title">${tr('instructions')}</h2><div class="v282-chips">${[['rush',tr('rush')],['stain',tr('stain')],['delicate',tr('delicate')],['defective',tr('defective')]].map(([id,l])=>`<button class="v282-chip ${counterDraft.tags.includes(id)?'sel':''}" onclick="posToggleTag('${id}')">${l}</button>`).join('')}</div><textarea class="v282-field" style="margin-top:14px" rows="3" placeholder="${tr('note')}" oninput="posSetNotes(this.value)">${esc2(counterDraft.notes)}</textarea>`}
const old=window.renderPosCounter;
window.renderPosCounter=function(content){if(!counterDraft)counterDraft=freshCounterDraft();let c=counterDraft.customerId?customerById(counterDraft.customerId):null;if(!c)K.step='customer';let body=K.step==='customer'?stageCustomer():K.step==='service'?stageService():K.step==='garment'?stageGarment():K.step==='qty'?stageQty():K.step==='color'?stageColor():K.step==='shirts'?stageShirts():K.step==='washfold'?stageWF():K.step==='alterations'?stageAlt():stageFinish();content.innerHTML=`<div class="v282-kiosk"><div class="v282-main">${header(c)}<div class="v282-stage">${body}<div class="v282-footer">${K.step!=='customer'?`<button class="v282-back" onclick="v282Step('${['qty','color'].includes(K.step)?'garment':K.step==='garment'?'service':K.step==='service'?'customer':'service'}')">← ${tr('back')}</button>`:''}${c&&counterDraft.items.length&&K.step!=='finish'?`<button class="v282-next" onclick="v282Step('finish')">${tr('next')} →</button>`:''}</div></div></div>${ticket()}</div>`};
window.v282Reset=function(){K.step='customer';K.qty=1;K.garment=null;};
const oldComplete=window.posCompleteDropOff; if(oldComplete) window.posCompleteDropOff=function(){let r=oldComplete.apply(this,arguments);K.step='customer';return r};
})();
