/* Hattan V28.2.4 — zero-scroll Drop Off kiosk + split-ticket multi-service + incremental AI intake */
(function(){
const T={
 en:{customer:'Find Customer',search:'Name / phone / address / customer #',service:'Choose Service',dryclean:'Dry Cleaning',shirts:'Laundered Shirts',washfold:'Wash & Fold',alterations:'Alterations',garment:'Choose Garment',qty:'How many?',color:'Choose Color',instructions:'Instructions & Finish',next:'Next',back:'Back',more:'More',pickup:'Customer Pickup',delivery:'Delivery',complete:'Complete & Print',empty:'No items yet',ticket:'Current Visit',edit:'Edit',remove:'Remove',stain:'Stain',delicate:'Delicate',defective:'Defective',rush:'RUSH',note:'Visit note',pounds:'Enter pounds',add:'Add',hanger:'On Hanger',box:'Boxed',none:'None',light:'Light',medium:'Medium',heavy:'Heavy',multi:'Multiple Services / Both',ai:'AI Speak / Type Intake',aihelp:'Type one line and press Enter. Keep typing and press Enter again to keep adding. Each service automatically becomes its own physical ticket.',price:'Price',start:'Start Selected Services',doneService:'Done With This Service',due:'Due',separate:'Separate ticket'},
 es:{customer:'Buscar cliente',search:'Nombre / teléfono / dirección / # cliente',service:'Elegir servicio',dryclean:'Limpieza en seco',shirts:'Camisas lavadas',washfold:'Lavado y doblado',alterations:'Arreglos',garment:'Elegir prenda',qty:'¿Cuántas?',color:'Elegir color',instructions:'Instrucciones y finalizar',next:'Siguiente',back:'Atrás',more:'Más',pickup:'Recoge cliente',delivery:'Entrega',complete:'Completar e imprimir',empty:'Sin prendas todavía',ticket:'Visita actual',edit:'Editar',remove:'Quitar',stain:'Mancha',delicate:'Delicado',defective:'Defectuoso',rush:'URGENTE',note:'Nota de visita',pounds:'Ingrese libras',add:'Agregar',hanger:'En gancho',box:'En caja',none:'Ninguno',light:'Ligero',medium:'Medio',heavy:'Fuerte',multi:'Varios servicios / Ambos',ai:'Entrada IA por voz / texto',aihelp:'Escriba una línea y presione Enter. Puede seguir escribiendo y presionar Enter otra vez. Cada servicio se convierte automáticamente en un ticket físico separado.',price:'Precio',start:'Comenzar servicios',doneService:'Terminar este servicio',due:'Fecha',separate:'Ticket separado'},
 zh:{customer:'查找顾客',search:'姓名 / 电话 / 地址 / 顾客编号',service:'选择服务',dryclean:'干洗',shirts:'衬衫水洗',washfold:'洗衣折叠',alterations:'修改衣服',garment:'选择衣物',qty:'数量',color:'选择颜色',instructions:'说明与完成',next:'下一步',back:'返回',more:'更多',pickup:'顾客自取',delivery:'送货',complete:'完成并打印',empty:'尚未添加衣物',ticket:'当前到店',edit:'编辑',remove:'删除',stain:'污渍',delicate:'精细衣物',defective:'有瑕疵',rush:'加急',note:'到店备注',pounds:'输入磅数',add:'添加',hanger:'挂装',box:'盒装',none:'无',light:'轻',medium:'中',heavy:'重',multi:'多种服务 / 同时',ai:'AI 语音 / 文字录入',aihelp:'输入一行后按 Enter。可以继续输入并再次按 Enter。每种服务会自动生成独立实体票据。',price:'价格',start:'开始所选服务',doneService:'完成此服务',due:'取件日期',separate:'独立票据'}
};
let K={step:'customer',lang:localStorage.getItem('hattanCounterLang')||'en',qty:1,garment:null,showMore:false,returnStep:'service',colorSelections:[],multiSelected:[],multiQueue:[],multiIndex:0,multiActive:false};
function tr(k){return (T[K.lang]||T.en)[k]||k}
function esc2(s){return window.esc?esc(s):String(s||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function svcName(s){return (window.V8_SERVICE_NAMES&&V8_SERVICE_NAMES[s])||({dryclean:'Dry Cleaning',shirts:'Laundered Shirts',washfold:'Wash & Fold',alterations:'Alterations'}[s]||s)}
function ensureShirtState(){counterDraft.shirts=counterDraft.shirts||{qty:1,packaging:'hanger',starch:'None'};if(!Array.isArray(counterDraft.shirts.colors))counterDraft.shirts.colors=[];}
function dueForGroup(g){counterDraft.serviceDueDates=counterDraft.serviceDueDates||{};return counterDraft.serviceDueDates[g.key]||counterDraft.serviceDueDates[g.service]||v8DefaultDue(g.service)}
window.v282Lang=function(l){K.lang=l;localStorage.setItem('hattanCounterLang',l);renderPosContent()};
window.v282Step=function(s){K.step=s;renderPosContent()};
window.v282Service=function(s,returnStep='service'){counterDraft.serviceMode=s;K.returnStep=returnStep;K.step=s==='dryclean'?'garment':s;renderPosContent()};
window.v282Qty=function(n){K.qty=n;K.colorSelections=[];K.step='color';renderPosContent()};
window.v282Garment=function(id){K.garment=id;K.colorSelections=[];K.step='qty';renderPosContent()};
window.v282UndoColor=function(){K.colorSelections.pop();renderPosContent()};
window.v282Color=function(id){
  if(!K.garment)return;K.colorSelections.push(id);
  if(K.colorSelections.length<K.qty){renderPosContent();return;}
  const garmentId=K.garment, materialId=counterDraft.builder?.materialId||'standard', g=garmentById(garmentId);
  K.colorSelections.slice(0,K.qty).forEach(colorId=>v9AddOrMergeLine({garmentId,materialId,colorId,qty:1,unitPrice:garmentUnitPrice(garmentId,materialId),buttonType:'standard',garmentNote:'',serviceType:'dryclean'}));
  counterDraft.serviceDueDates=counterDraft.serviceDueDates||{};counterDraft.serviceDueDates.dryclean||=v8DefaultDue('dryclean');
  toast(`${K.qty} ${g?.name||'item'}${K.qty===1?'':'s'} added with ${K.qty} color entr${K.qty===1?'y':'ies'}`,true,'checkcircle');
  K.garment=null;K.qty=1;K.colorSelections=[];K.step='garment';renderPosContent();
};
window.v282Pick=function(id){K.step='service';posPickCustomer(id);renderPosContent()};
window.v282Search=function(v){posCustomerSearch=v;renderPosContent();setTimeout(()=>{let x=document.getElementById('v282search');if(x){x.focus();x.setSelectionRange(x.value.length,x.value.length)}},0)};
window.v282SearchKey=function(e){if(e.key!=='Enter')return;let q=String(posCustomerSearch||'').trim().toLowerCase();if(!q)return;let r=state.customers.filter(c=>[c.name,c.phone,c.address,c.customerNumber].some(x=>String(x||'').toLowerCase().includes(q))).slice(0,8);if(r.length===1){e.preventDefault();v282Pick(r[0].id)}};
window.v282More=function(){K.showMore=!K.showMore;renderPosContent()};
window.v282SetFulfill=function(v){counterDraft.fulfillment=v;renderPosContent()};
window.v282EditItem=function(i){const it=counterDraft.items[i];if(!it)return;const g=garmentById(it.garmentId);openPosModal(`<h3>Edit ${esc2(g?.name||'Item')}</h3><div class="form-grid"><label>Quantity<input id="v282-edit-qty" class="text-input" type="number" min=".1" step=".1" value="${esc2(it.qty)}"></label><label>${tr('price')}<input id="v282-edit-price" class="text-input" type="number" min="0" step=".01" value="${esc2(it.unitPrice)}"></label></div><label style="display:block;margin-top:10px">Color<select id="v282-edit-color" class="text-input">${GARMENT_COLORS.map(x=>`<option value="${x.id}" ${x.id===it.colorId?'selected':''}>${esc2(x.name)}</option>`).join('')}</select></label><label style="display:block;margin-top:10px">Notes<input id="v282-edit-note" class="text-input" value="${esc2(it.garmentNote||'')}"></label><button class="btn btn-primary btn-block" style="margin-top:14px" onclick="v282SaveEdit(${i})">Save Changes</button>`)};
window.v282SaveEdit=function(i){const it=counterDraft.items[i];if(!it)return;it.qty=Math.max(.1,Number(document.getElementById('v282-edit-qty')?.value||it.qty));it.unitPrice=Math.max(0,Number(document.getElementById('v282-edit-price')?.value||it.unitPrice));it.colorId=document.getElementById('v282-edit-color')?.value||it.colorId;it.garmentNote=document.getElementById('v282-edit-note')?.value||'';closePosModal();renderPosContent()};

/* Faster multiple-service workflow: select all services once, then advance through them. */
window.v282OpenMulti=function(){K.multiSelected=[];K.multiQueue=[];K.multiIndex=0;K.multiActive=false;K.step='multi';renderPosContent()};
window.v282ToggleMulti=function(s){const i=K.multiSelected.indexOf(s);if(i>=0)K.multiSelected.splice(i,1);else K.multiSelected.push(s);renderPosContent()};
window.v282StartMulti=function(){if(K.multiSelected.length<2)return toast('Choose at least two services',false,'alerttriangle');K.multiQueue=['dryclean','shirts','washfold','alterations'].filter(s=>K.multiSelected.includes(s));K.multiIndex=0;K.multiActive=true;v282Service(K.multiQueue[0],'multiFlow')};
window.v282AdvanceMulti=function(){if(!K.multiActive){K.step='service';renderPosContent();return;}K.multiIndex++;if(K.multiIndex<K.multiQueue.length){v282Service(K.multiQueue[K.multiIndex],'multiFlow')}else{K.multiActive=false;K.step='finish';renderPosContent()}};
window.v282DoneDry=function(){v282AdvanceMulti()};

/* Shirts require one color entry per shirt; repeated colors are allowed but never assumed. */
window.v282ShirtQty=function(n){ensureShirtState();counterDraft.shirts.qty=n;counterDraft.shirts.colors=[];renderPosContent()};
window.v282ShirtColor=function(id){ensureShirtState();if(counterDraft.shirts.colors.length>=counterDraft.shirts.qty)return;counterDraft.shirts.colors.push(id);renderPosContent()};
window.v282UndoShirtColor=function(){ensureShirtState();counterDraft.shirts.colors.pop();renderPosContent()};
window.v282AddShirts=function(){
  ensureShirtState();const s=counterDraft.shirts;if(s.colors.length!==Number(s.qty||0))return toast(`Choose ${s.qty} shirt color${s.qty===1?'':'s'} first`,false,'alerttriangle');
  const id=s.packaging==='box'?'g_lshirt_box':'g_lshirt',g=garmentById(id)||state.garmentCatalog.find(x=>x.id===id);if(!g)return;
  s.colors.forEach(colorId=>v9AddOrMergeLine({garmentId:g.id,materialId:'standard',colorId,qty:1,unitPrice:g.basePrice,buttonType:'standard',garmentNote:`${s.packaging==='box'?'Boxed':'On hanger'} · Starch: ${s.starch}`,serviceType:'shirts'}));
  counterDraft.serviceDueDates=counterDraft.serviceDueDates||{};counterDraft.serviceDueDates.shirts||=v8DefaultDue('shirts');
  counterDraft.shirts={qty:1,packaging:'hanger',starch:'None',colors:[]};toast('Laundered shirts added',true,'checkcircle');if(K.multiActive)v282AdvanceMulti();else{K.step='service';renderPosContent()}
};
window.v282AddWF=function(){v4AddWashFold();if(K.multiActive)v282AdvanceMulti();else{K.step='service';renderPosContent()}};
window.v282AddAlt=function(){v4AddAlteration();if(K.multiActive)v282AdvanceMulti();else{K.step='service';renderPosContent()}};

/* Incremental AI: Enter adds the current line to the live visit, clears the box, and stays ready for another Enter. */
window.v282AiEnter=function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(typeof v23TypedIntakeSubmit==='function')v23TypedIntakeSubmit();}};
window.v282AiAdd=function(){if(typeof v23TypedIntakeSubmit==='function')v23TypedIntakeSubmit()};
window.v282VoiceAdd=function(){const voice=String(document.getElementById('v3-ai-transcript')?.value||counterDraft.aiTranscript||'').trim();if(!voice)return toast('Speak first or type into the box',false,'alerttriangle');const typed=document.getElementById('v23-ai-entry');if(typed)typed.value=voice;if(typeof v23TypedIntakeSubmit==='function')v23TypedIntakeSubmit();counterDraft.aiTranscript='';const box=document.getElementById('v3-ai-transcript');if(box)box.value='';};

function groupTicket(){
  const d=counterDraft,groups=v8DraftGroups();
  return `<div class="v282-ticket"><h3>${tr('ticket')} · ${groups.length} ${tr('separate')}${groups.length===1?'':'s'}</h3><div class="v282-lines">${groups.length?groups.map((group,gi)=>{
    const key=group.key||group.service,date=dueForGroup(group),sub=v8ServiceSubtotal(group.items),future=Number(state.nextTicket||0)+gi;
    return `<div class="v282-subticket"><div class="v282-subticket-head"><div><strong>#${future} · ${esc2(svcName(group.service))}</strong><small>${group.items.length} line${group.items.length===1?'':'s'} · ${money(sub)}</small></div><label>${tr('due')}<input type="date" value="${esc2(date)}" onchange="v14SetDueDate('${esc2(key)}',this.value,false)"></label></div>${group.items.map(it=>{const i=d.items.indexOf(it),g=garmentById(it.garmentId),c=colorById(it.colorId);return `<div class="v282-line"><div class="v282-line-top"><strong>${esc2(g?.name||'Item')} × ${it.qty}</strong><strong class="v282-line-price">${money(Number(it.unitPrice||0)*Number(it.qty||0))}</strong></div><div>${esc2(c?.name||'')} ${it.garmentNote?' · '+esc2(it.garmentNote):''}</div><div class="v282-line-buttons"><button onclick="v282EditItem(${i})">${tr('edit')}</button><button onclick="posRemoveItem(${i})">${tr('remove')}</button></div></div>`}).join('')}</div>`
  }).join(''):`<div class="ticket-empty">${tr('empty')}</div>`}</div><div class="v282-total">${money(posTicketTotal())}</div><div class="v282-actions"><button class="${d.fulfillment==='pickup'?'sel':''}" onclick="v282SetFulfill('pickup')">${tr('pickup')}</button><button class="${d.fulfillment==='delivery'?'sel':''}" onclick="v282SetFulfill('delivery')">${tr('delivery')}</button>${groups.length?`<button class="v282-complete" onclick="posCompleteDropOff()">${tr('complete')} ${groups.length} Ticket${groups.length===1?'':'s'}</button>`:''}</div></div>`;
}
function header(c){return `<div class="v282-head"><div>${c?`<div class="v282-customer">${esc2(c.name)} · ${esc2(c.customerNumber||'')}</div><div class="v282-sub">${esc2(c.phone||'')} ${c.address?' · '+esc2(c.address):''}</div>`:`<div class="v282-customer">Hattan Drop Off</div><div class="v282-sub">V28.2.4 · Split-ticket zero-scroll counter</div>`}</div><div class="v282-lang"><button class="${K.lang==='en'?'on':''}" onclick="v282Lang('en')">EN</button><button class="${K.lang==='es'?'on':''}" onclick="v282Lang('es')">ES</button><button class="${K.lang==='zh'?'on':''}" onclick="v282Lang('zh')">中文</button></div></div>`}
function stageCustomer(){let q=posCustomerSearch.trim().toLowerCase(),r=q?state.customers.filter(c=>[c.name,c.phone,c.address,c.customerNumber].some(x=>String(x||'').toLowerCase().includes(q))).slice(0,8):[];return `<h2 class="v282-title">${tr('customer')}</h2><input id="v282search" autofocus class="v282-search" placeholder="${tr('search')}" value="${esc2(posCustomerSearch)}" oninput="v282Search(this.value)" onkeydown="v282SearchKey(event)"><div class="v282-results">${r.map(c=>`<div class="v282-result" onclick="v282Pick('${c.id}')">${esc2(c.name)}<small style="display:block">${esc2(c.phone||'')} · ${esc2(c.address||c.customerNumber||'')}</small></div>`).join('')}</div>`}
function stageService(){return `<h2 class="v282-title">${tr('service')}</h2><div class="v282-grid"><button class="v282-big" onclick="v282Service('dryclean')">${tr('dryclean')}</button><button class="v282-big" onclick="v282Service('shirts')">${tr('shirts')}</button><button class="v282-big" onclick="v282Service('washfold')">${tr('washfold')}</button><button class="v282-big" onclick="v282Service('alterations')">${tr('alterations')}</button><button class="v282-big v282-multi" onclick="v282OpenMulti()">${tr('multi')}<small>Select all services once, then move straight through them</small></button><button class="v282-big v282-ai" onclick="v282Step('ai')">✨ ${tr('ai')}<small>Press Enter repeatedly to add</small></button></div>`}
function stageMulti(){const services=['dryclean','shirts','washfold','alterations'];return `<h2 class="v282-title">${tr('multi')}</h2><div class="v282-help">Tap every service in this visit. Then press Start once. The POS will walk through only those services and create separate tickets with separate due dates.</div><div class="v282-grid">${services.map(s=>`<button class="v282-big v282-selectable ${K.multiSelected.includes(s)?'sel':''}" onclick="v282ToggleMulti('${s}')">${K.multiSelected.includes(s)?'✓ ':''}${tr(s)}</button>`).join('')}</div><button class="v282-next v282-start-multi" onclick="v282StartMulti()" ${K.multiSelected.length<2?'disabled':''}>${tr('start')} · ${K.multiSelected.length}</button>`}
function stageAI(){let review=counterDraft.aiInterpretation;return `<h2 class="v282-title">✨ ${tr('ai')}</h2><div class="v282-help">${tr('aihelp')} You do NOT need to say “separate ticket” just because the service changes — Dry Cleaning, Shirts, Wash & Fold and Alterations automatically split. Use “separate ticket” only if you want two physical tickets for the same service.</div><div class="v282-ai-box"><textarea id="v23-ai-entry" autofocus class="v282-ai-text" rows="3" onkeydown="v282AiEnter(event)" placeholder="Example: 2 navy pants dry clean tomorrow — press Enter\n4 shirts on hanger, 2 white 1 blue 1 pink Friday — press Enter\n12 pounds wash and fold Monday — press Enter"></textarea><div class="v282-ai-actions"><button class="v282-next" onclick="v282AiAdd()">＋ Add / Enter</button><span>Enter adds immediately to the visit and clears this box.</span></div><div class="v282-ai-row"><button type="button" id="v3-mic-btn" class="v282-mic ${counterDraft.aiListening?'listening':''}" onclick="posToggleAiVoice()" ${posVoiceSupported()?'':'disabled'}>🎙 Speak</button><span id="v3-mic-status">Voice uses the same incremental parser.</span></div><textarea id="v3-ai-transcript" class="v282-ai-text" rows="2" oninput="counterDraft.aiTranscript=this.value" placeholder="Voice transcript appears here…">${esc2(counterDraft.aiTranscript||'')}</textarea><button class="v282-next" onclick="v282VoiceAdd()">✨ Add Voice to Visit</button>${review?`<div class="v282-ai-review"><strong>${esc2(review.summary||'Added')}</strong>${(review.lines||[]).map(x=>`<div>${esc2(x)}</div>`).join('')}${review.warnings?.length?`<div class="v282-ai-warn">Verify: ${review.warnings.map(esc2).join(' ')}</div>`:''}</div>`:''}</div>`}
function stageGarment(){let ids=(state.interfaceSettings?.drycleanOrder||[]),show=K.showMore?ids:ids.slice(0,9);return `<h2 class="v282-title">${tr('garment')}</h2><div class="v282-grid">${show.map(id=>{let g=garmentById(id);return g?`<button class="v282-big" onclick="v282Garment('${id}')">${esc2(g.name)}<small>${money(g.basePrice)}</small></button>`:''}).join('')}${ids.length>9?`<button class="v282-big" onclick="v282More()">${tr('more')} →</button>`:''}</div>${K.multiActive?`<button class="v282-next v282-service-done" onclick="v282DoneDry()">${tr('doneService')} →</button>`:''}`}
function stageQty(){return `<h2 class="v282-title">${tr('qty')}</h2><div class="v282-qty">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<button onclick="v282Qty(${n})">${n}</button>`).join('')}</div>`}
function stageColor(){const selected=K.colorSelections.map(id=>colorById(id)?.name||id);return `<h2 class="v282-title">${tr('color')} · ${K.colorSelections.length+1} of ${K.qty}</h2><div class="v282-help">Quantity ${K.qty} means you must enter ${K.qty} colors. Tap the same color more than once only if multiple garments really are that color.</div>${selected.length?`<div class="v282-color-progress">${selected.map((x,i)=>`<span>${i+1}. ${esc2(x)}</span>`).join('')}<button onclick="v282UndoColor()">Undo last</button></div>`:''}<div class="v282-colors">${GARMENT_COLORS.map(c=>`<button class="v282-color" onclick="v282Color('${c.id}')"><i style="background:${c.sw}"></i>${esc2(c.name)}</button>`).join('')}</div>`}
function stageShirts(){ensureShirtState();const s=counterDraft.shirts,selected=s.colors.map(id=>colorById(id)?.name||id),remaining=Math.max(0,s.qty-s.colors.length);return `<h2 class="v282-title">${tr('shirts')}</h2><div class="v282-qty">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<button onclick="v282ShirtQty(${n})" class="${s.qty===n?'sel':''}">${n}</button>`).join('')}</div><div class="v282-help">Choose ${s.qty} shirt color${s.qty===1?'':'s'} — one color entry per shirt. ${remaining?`${remaining} remaining.`:'All colors entered.'}</div>${selected.length?`<div class="v282-color-progress">${selected.map((x,i)=>`<span>${i+1}. ${esc2(x)}</span>`).join('')}<button onclick="v282UndoShirtColor()">Undo last</button></div>`:''}<div class="v282-colors v282-shirt-colors">${GARMENT_COLORS.map(c=>`<button class="v282-color" onclick="v282ShirtColor('${c.id}')" ${remaining?'':'disabled'}><i style="background:${c.sw}"></i>${esc2(c.name)}</button>`).join('')}</div><div class="v282-chips"><button class="v282-chip ${s.packaging==='hanger'?'sel':''}" onclick="v4SetShirtPackaging('hanger')">${tr('hanger')}</button><button class="v282-chip ${s.packaging==='box'?'sel':''}" onclick="v4SetShirtPackaging('box')">${tr('box')}</button>${['None','Light','Medium','Heavy'].map(x=>`<button class="v282-chip ${s.starch===x?'sel':''}" onclick="v4SetStarch('${x}')">${tr(x.toLowerCase())}</button>`).join('')}</div><button class="v282-next" onclick="v282AddShirts()" ${remaining?'disabled':''}>${tr('add')} ${s.qty} Shirt${s.qty===1?'':'s'}</button>`}
function stageWF(){return `<h2 class="v282-title">${tr('washfold')}</h2><input class="v282-field" type="number" step=".1" placeholder="${tr('pounds')}" value="${esc2(counterDraft.wf.pounds)}" oninput="v4SetWfField('pounds',this.value)"><div class="v282-grid four">${['Black','White','Blue','Red','Green','Gray','Pink','Other'].map(c=>`<button class="v282-big ${counterDraft.wf.bagColor===c?'sel':''}" onclick="v4SetWfField('bagColor','${c}');renderPosContent()">${c}</button>`).join('')}</div><button class="v282-next" onclick="v282AddWF()">${tr('add')} ${tr('washfold')}</button>`}
function stageAlt(){let arr=(state.interfaceSettings?.alterationOrder||[]).slice(0,12);return `<h2 class="v282-title">${tr('alterations')}</h2><div class="v282-grid four">${arr.map(id=>{let a=ALTERATION_VARIANTS.find(x=>x.id===id);return a?`<button class="v282-big ${counterDraft.alteration.variantId===id?'sel':''}" onclick="v4SetAlterVariant('${id}')">${esc2(a.garment)}<small>${esc2(a.name)} · ${a.price?money(a.price):'Quoted'}</small></button>`:''}).join('')}</div><input class="v282-field" style="margin-top:12px" placeholder="Details / notes" value="${esc2(counterDraft.alteration.additionalInfo)}" oninput="counterDraft.alteration.additionalInfo=this.value"><button class="v282-next" onclick="v282AddAlt()">${tr('add')} ${tr('alterations')}</button>`}
function stageFinish(){return `<h2 class="v282-title">${tr('instructions')}</h2><div class="v282-help">Each service is already a separate physical ticket. Set each ticket's due date independently in the right-hand panel before Complete & Print.</div><div class="v282-chips">${[['rush',tr('rush')],['stain',tr('stain')],['delicate',tr('delicate')],['defective',tr('defective')]].map(([id,l])=>`<button class="v282-chip ${counterDraft.tags.includes(id)?'sel':''}" onclick="posToggleTag('${id}')">${l}</button>`).join('')}</div><textarea class="v282-field" style="margin-top:14px" rows="3" placeholder="${tr('note')}" oninput="posSetNotes(this.value)">${esc2(counterDraft.notes)}</textarea>`}
const old=window.renderPosCounter;
window.renderPosCounter=function(content){if(!counterDraft)counterDraft=freshCounterDraft();ensureShirtState();let c=counterDraft.customerId?customerById(counterDraft.customerId):null;if(!c)K.step='customer';let body=K.step==='customer'?stageCustomer():K.step==='service'?stageService():K.step==='multi'?stageMulti():K.step==='ai'?stageAI():K.step==='garment'?stageGarment():K.step==='qty'?stageQty():K.step==='color'?stageColor():K.step==='shirts'?stageShirts():K.step==='washfold'?stageWF():K.step==='alterations'?stageAlt():stageFinish();
  const backTarget=['qty','color'].includes(K.step)?'garment':K.step==='garment'?(K.multiActive?'multi':'service'):K.step==='service'?'customer':K.step==='multi'?'service':K.step==='ai'?'service':(K.multiActive?'multi':'service');
  content.innerHTML=`<div class="v282-kiosk"><div class="v282-main">${header(c)}<div class="v282-stage">${body}<div class="v282-footer">${K.step!=='customer'?`<button class="v282-back" onclick="v282Step('${backTarget}')">← ${tr('back')}</button>`:''}${c&&counterDraft.items.length&&!['finish','multi'].includes(K.step)?`<button class="v282-next" onclick="v282Step('finish')">${tr('next')} →</button>`:''}</div></div></div>${groupTicket()}</div>`;
  if(K.step==='ai')requestAnimationFrame(()=>document.getElementById('v23-ai-entry')?.focus());
};
window.v282Reset=function(){K.step='customer';K.qty=1;K.garment=null;K.returnStep='service';K.colorSelections=[];K.multiSelected=[];K.multiQueue=[];K.multiIndex=0;K.multiActive=false};
const oldComplete=window.posCompleteDropOff;if(oldComplete)window.posCompleteDropOff=function(){let r=oldComplete.apply(this,arguments);v282Reset();return r};
})();
